import React from "react";

import './globals.css'
import Header from "@/components/ui/header/Header";


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

// export default async function RootLayout({children}: { children: React.ReactNode }
export default function RootLayout({children}: { children: React.ReactNode }
) {
    return (
        <html lang="en">
        <head></head>
        <body>
        {/*<NextAuthProvider>*/}
            <Header/>
            <main>
                {children}
            </main>
            {/*<Footer/>*/}
        {/*</NextAuthProvider>*/}
        </body>
        </html>
    );
}